### ISSUE TITLE
SAME fails to install

### ISSUE THREAD

**Issue by js-ts** [SAME-Project/same-project#106]
`
Building wheels for collected packages: Cerberus, cytoolz, kfp
  Building wheel for Cerberus (PEP 517) ... done
  Created wheel for Cerberus: filename=Cerberus-1.3.4-py3-none-any.whl size=58196 sha256=f810522c4486f42fd1fde9eb07d8de0bf44858780f09518aec71f9cabd5bc190
  Stored in directory: /home/jovyan/.cache/pip/wheels/92/1e/40/307520b5eb38ceae17d32d7d7920e3e5eee6f4cd78cfd75ac7
  Building wheel for cytoolz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-20xt5gml/cytoolz_66c323df82ff4dc28e4c1e79524db6b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-20xt5gml/cytoolz_66c323df82ff4dc28e4c1e79524db6b1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-21qby8sh
       cwd: /tmp/pip-install-20xt5gml/cytoolz_66c323df82ff4dc28e4c1e79524db6b1/
  Complete output (57 lines):
  [1/5] Cythonizing cytoolz/utils.pyx
  [2/5] Cythonizing cytoolz/dicttoolz.pyx
  [3/5] Cythonizing cytoolz/functoolz.pyx
  [4/5] Cythonizing cytoolz/itertoolz.pyx
  [5/5] Cythonizing cytoolz/recipes.pyx
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/_version.py -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.8/cytoolz
  creating build/lib.linux-x86_64-3.8/cytoolz/curried
  copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
  copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
  copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
  copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.8/cytoolz
  copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.8/cytoolz
  creating build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
  running build_ext
  building 'cytoolz.dicttoolz' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/cytoolz
  gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.8 -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.8/cytoolz/dicttoolz.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
  Building wheel for kfp (setup.py) ... done
  Created wheel for kfp: filename=kfp-1.8.12-py3-none-any.whl size=419051 sha256=2a01890e58c91c866baeee88594b02a79e738bafec0f53f83d70ecb605f866fb
  Stored in directory: /home/jovyan/.cache/pip/wheels/98/fb/f1/59e0d57d91d3962c874739f5d1c9fa66526b67c24805d034e6
Successfully built Cerberus kfp
Failed to build cytoolz
Installing collected packages: pyzmq, python-dateutil, nest-asyncio, jupyter-core, jupyter-client, charset-normalizer, requests, mdurl, typing-extensions, qtpy, markdown-it-py, wimpy, typer, toml, structlog, ruamel.yaml.clib, qtconsole, pydantic, pkginfo, oyaml, mdit-py-plugins, kubernetes, kfp-pipeline-spec, jupyter-console, distlib, cloudpickle, anytree, tblib, ruamel.yaml, regex, python-box, pandas, metakernel, kfp, jupytext, jupyter, johnnydep, cytoolz, Cerberus, sameproject
  Attempting uninstall: pyzmq
    Found existing installation: pyzmq 22.1.0
    Uninstalling pyzmq-22.1.0:
      Successfully uninstalled pyzmq-22.1.0
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.1
    Uninstalling python-dateutil-2.8.1:
      Successfully uninstalled python-dateutil-2.8.1
  Attempting uninstall: nest-asyncio
    Found existing installation: nest-asyncio 1.5.1
    Uninstalling nest-asyncio-1.5.1:
      Successfully uninstalled nest-asyncio-1.5.1
  Attempting uninstall: jupyter-core
    Found existing installation: jupyter-core 4.7.1
    Uninstalling jupyter-core-4.7.1:
      Successfully uninstalled jupyter-core-4.7.1
  Attempting uninstall: jupyter-client
    Found existing installation: jupyter-client 6.1.12
    Uninstalling jupyter-client-6.1.12:
      Successfully uninstalled jupyter-client-6.1.12
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 4.0.1
    Uninstalling typing-extensions-4.0.1:
      Successfully uninstalled typing-extensions-4.0.1
  Attempting uninstall: kubernetes
    Found existing installation: kubernetes 12.0.1
    Uninstalling kubernetes-12.0.1:
      Successfully uninstalled kubernetes-12.0.1
  Attempting uninstall: kfp-pipeline-spec
    Found existing installation: kfp-pipeline-spec 0.1.13
    Uninstalling kfp-pipeline-spec-0.1.13:
      Successfully uninstalled kfp-pipeline-spec-0.1.13
  Attempting uninstall: cloudpickle
    Found existing installation: cloudpickle 1.6.0
    Uninstalling cloudpickle-1.6.0:
      Successfully uninstalled cloudpickle-1.6.0
  Attempting uninstall: pandas
    Found existing installation: pandas 1.2.4
    Uninstalling pandas-1.2.4:
      Successfully uninstalled pandas-1.2.4
  Attempting uninstall: kfp
    Found existing installation: kfp 1.6.3
    Uninstalling kfp-1.6.3:
      Successfully uninstalled kfp-1.6.3
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-20xt5gml/cytoolz_66c323df82ff4dc28e4c1e79524db6b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-20xt5gml/cytoolz_66c323df82ff4dc28e4c1e79524db6b1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-og9a9po7/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.8/cytoolz
         cwd: /tmp/pip-install-20xt5gml/cytoolz_66c323df82ff4dc28e4c1e79524db6b1/
    Complete output (57 lines):
    [1/5] Cythonizing cytoolz/utils.pyx
    [2/5] Cythonizing cytoolz/dicttoolz.pyx
    [3/5] Cythonizing cytoolz/functoolz.pyx
    [4/5] Cythonizing cytoolz/itertoolz.pyx
    [5/5] Cythonizing cytoolz/recipes.pyx
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/_version.py -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.8/cytoolz
    creating build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    creating build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/cytoolz
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.8 -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.8/cytoolz/dicttoolz.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-20xt5gml/cytoolz_66c323df82ff4dc28e4c1e79524db6b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-20xt5gml/cytoolz_66c323df82ff4dc28e4c1e79524db6b1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-og9a9po7/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.8/cytoolz Check the logs for full command output.
(base) jovyan@same-test-0:~$ python --version
Python 3.8.10
`

**Comment by aronchick** [comment]
Can you describe the debugging steps you went through here? For example, just before the dashes, it says "gcc" is not installed. What happens when you install it?

**Comment by aronchick** [comment]
We need a bunch more repro steps here - what environment were you in? how did you try to install? etc

**Comment by aronchick** [comment]
Can you also upload the entire log? Not just this - we need what happened before this.
