### ISSUE TITLE
module imports no longer seem to persist across steps

### ISSUE THREAD

**Issue by lukemarsden** [SAME-Project/same-project#130]
This notebook: https://github.com/SAME-Project/SAME-samples/blob/multi-stage-pipeline/03-road-signs/roadsigns.ipynb

Now fails like this:
<img width="2513" alt="Screenshot 2022-05-09 at 14 12 35" src="https://user-images.githubusercontent.com/264658/167418558-27939c92-2498-4b81-b8e0-3505a3a67a3f.png">

(latest `main` as of today)

Possibly a regression due to adding the exploding variables support?

**Comment by Bubblyworld** [comment]
Looks like it's correctly replacing the CSV reader with an exploding
variable, but then trying to check the mem size of the exploding variable
(which subsequently explodes as designed). So we should do mem check first.

**Comment by lukemarsden** [comment]
All good! No rush sir! Enjoy your evening 😄
