### ISSUE TITLE
move docs repo in here

### ISSUE THREAD

**Issue by lukemarsden** [SAME-Project/same-project#33]
The docs repo at https://github.com/SAME-Project/SAME-Docs should be in the monorepo, so that docs changes can be included alongside code changes in PRs.

- [x] copy the docs in
- [x] archive the docs repo with a note in the readme pointing here

**Comment by js-ts** [comment]
@lukemarsden can you add https://github.com/SAME-Project/SAME-installer-website to the repos to be archived along with docs
