### ISSUE TITLE
Documentation is not accessible by anyone outside of MS AD

### ISSUE THREAD

**Issue by pyousefi** [SAME-Project/same-project#57]
https://samedocs.azurewebsites.net/getting-started/dev-build/ cannot be accessed by users from IQVIA's imshealth.com AD domain.

**Comment by js-ts** [comment]
@pyousefi the documentation has moved to https://sameproject.ml/
https://sameproject.ml/getting-started/installing/

**Comment by pyousefi** [comment]
@js-ts , this is from the readme: https://github.com/SAME-Project/same-project#getting-started
"Refer to the SAME Project docs for building and running this repo." There is no documentation for building and running this repo. The closest thing I found is this: https://sameproject.ml/getting-started/dev-build/ which references another repo.

**Comment by Bubblyworld** [comment]
These links have been fixed now.
