### ISSUE TITLE
Enable forked repos to contribute PRs without permission errors

### ISSUE THREAD

**Issue by lukemarsden** [SAME-Project/same-project#61]
example: https://github.com/SAME-Project/same-project/runs/5228905644?check_suite_focus=true

**Comment by annajung** [comment]
I'll pick this up and try to find a solution or a workaround

**Comment by annajung** [comment]
According to the [GitHub blog post](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/), they introduced [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) that behaves the almost same way as the `pull_request` event. Unlike use of `pull_request` that limits the `GITHUB_TOKEN` to read access for forked repo, `pull_request_target` will grant **write** permission for forked repos that will allow the bot to post a comment on the pull request.

However, given that write access is given to anyone who forks the repo, it is not recommended to run the workflow on untrusted code and recommends the use of labels to indicate PR has been vetted.

@lukemarsden @aronchick @js-ts What do you think about adding `needs-ok-to-test` labels (automatically using github actions) to indicate that PR needs to be vetted and once vetted, those who have access to add labels can add `ok-to-test` label to trigger the workflow.

**Comment by lukemarsden** [comment]
Yes please!

**Comment by annajung** [comment]
Sorry for the delay, was out all last week. Created a PR to test out the actions https://github.com/SAME-Project/same-project/pull/87, looks like it might have been fixed. Could someone help add the label `ok-to-test` to test out the actions?

**Comment by annajung** [comment]
We can close this issue now (I don't have permission to close)

- Based on https://github.com/SAME-Project/same-project/pull/87, it was tested that an issue with the label not working has been fixed by @Bubblyworld
- PR also test that when `ok-to-test` label is applied, the rest of the CI workflow runs

Thanks!
