### ISSUE TITLE
Splitting the roadsigns demo into multiple pipeline steps and showing that working

### ISSUE THREAD

**Issue by lukemarsden** [SAME-Project/same-project#81]

**Comment by Bubblyworld** [comment]
<img width="990" alt="Screenshot 2022-04-01 at 00 10 41" src="https://user-images.githubusercontent.com/6214591/161538069-17c84fb7-2cd7-4db9-baf6-c37d6f02ef9d.png">

Shweet, splitting the roadsign demo into multiple steps and running it works fine now!

There's still an issue with serialising keras models (not a problem in this specific case), I'll make an issue for it.
